### ISSUE TITLE
Todo until Monday

### ISSUE THREAD

**Issue by tobiasraabe** [tobiasraabe/loc#29]
**DEADLINE**: tomorrow lunch

**Imke**:
- [ ] prepare three regressions
- [x] clustering hh_id
- BREAK regressions review
- [x] discussion fixed effects and clustering
- [x] make regression with time dummies instead of continous variables [Tobias: No need to do that. I will take care of it when I have your third specification.]
- [x] discuss inclusion of interaction terms etc.
- [x] discuss internal vs exaternal types (Buddelmeyer, etc.)
- [ ] write conclusion
    - [ ] improvements for future research
    - [ ] examing the learning effect from context to stable LOC
    - [ ] critical time periods for establishment of LOC

**Tobias**:
- [x] change disability als event
- [x] create LAST_JOB_ENDED and LAST_JOB_ENDED_LIMITED to have the last job spec from preuss hennecke
- [x] make index loc (drop ambigious item and cultural)
- [x] pca with 7 and 10 items
- [x] descriptives for individuals in the first period 2005, 2010
- [x] nonparametric level test for those without and with events
- [ ] make graphic on heterogenous time effects

**Later**:
- make analysis regarding different age effects
- restrict to ind with no event in first period to exclude lagged effects.
- restrict sample to use fe
- sample restriction test for PReuss Hennecke
